import { ITable } from '../../lib/sqlike';

export interface ActorTable {
  actor_id: number;
  first_name: string;
  last_name: string;
  last_update: Date;
}

export const actorTable: ITable<ActorTable> = {
  name: 'actor',
  fields: {
    actor_id: {
      name: 'actor_id',
      table: 'actor',
      data_type: 'numeric',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: true,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    first_name: {
      name: 'first_name',
      table: 'actor',
      data_type: 'varchar',
      default_value: null,
      max_length: 45,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    last_name: {
      name: 'last_name',
      table: 'actor',
      data_type: 'varchar',
      default_value: null,
      max_length: 45,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    last_update: {
      name: 'last_update',
      table: 'actor',
      data_type: 'timestamp',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
  },
};

export interface CountryTable {
  country_id: number;
  country: string;
  last_update: Date;
}

export const countryTable: ITable<CountryTable> = {
  name: 'country',
  fields: {
    country_id: {
      name: 'country_id',
      table: 'country',
      data_type: 'smallint',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: true,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    country: {
      name: 'country',
      table: 'country',
      data_type: 'varchar',
      default_value: null,
      max_length: 50,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    last_update: {
      name: 'last_update',
      table: 'country',
      data_type: 'timestamp',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: true,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
  },
};

export interface CityTable {
  city_id: number;
  city: string;
  country_id: number;
  last_update: Date;
}

export const cityTable: ITable<CityTable> = {
  name: 'city',
  fields: {
    city_id: {
      name: 'city_id',
      table: 'city',
      data_type: 'int',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: true,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    city: {
      name: 'city',
      table: 'city',
      data_type: 'varchar',
      default_value: null,
      max_length: 50,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    country_id: {
      name: 'country_id',
      table: 'city',
      data_type: 'smallint',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: 'country_id',
      foreign_key_table: 'country',
    },
    last_update: {
      name: 'last_update',
      table: 'city',
      data_type: 'timestamp',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
  },
};

export interface AddressTable {
  address_id: number;
  address: string;
  address2: string;
  district: string;
  city_id: number;
  postal_code: string;
  phone: string;
  last_update: Date;
}

export const addressTable: ITable<AddressTable> = {
  name: 'address',
  fields: {
    address_id: {
      name: 'address_id',
      table: 'address',
      data_type: 'int',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: true,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    address: {
      name: 'address',
      table: 'address',
      data_type: 'varchar',
      default_value: null,
      max_length: 50,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    address2: {
      name: 'address2',
      table: 'address',
      data_type: 'varchar',
      default_value: 'NULL',
      max_length: 50,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: true,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    district: {
      name: 'district',
      table: 'address',
      data_type: 'varchar',
      default_value: null,
      max_length: 20,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    city_id: {
      name: 'city_id',
      table: 'address',
      data_type: 'int',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: 'city_id',
      foreign_key_table: 'city',
    },
    postal_code: {
      name: 'postal_code',
      table: 'address',
      data_type: 'varchar',
      default_value: 'NULL',
      max_length: 10,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: true,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    phone: {
      name: 'phone',
      table: 'address',
      data_type: 'varchar',
      default_value: null,
      max_length: 20,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    last_update: {
      name: 'last_update',
      table: 'address',
      data_type: 'timestamp',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
  },
};

export interface LanguageTable {
  language_id: number;
  name: string;
  last_update: Date;
}

export const languageTable: ITable<LanguageTable> = {
  name: 'language',
  fields: {
    language_id: {
      name: 'language_id',
      table: 'language',
      data_type: 'smallint',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: true,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    name: {
      name: 'name',
      table: 'language',
      data_type: 'char',
      default_value: null,
      max_length: 20,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    last_update: {
      name: 'last_update',
      table: 'language',
      data_type: 'timestamp',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
  },
};

export interface CategoryTable {
  category_id: number;
  name: string;
  last_update: Date;
}

export const categoryTable: ITable<CategoryTable> = {
  name: 'category',
  fields: {
    category_id: {
      name: 'category_id',
      table: 'category',
      data_type: 'smallint',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: true,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    name: {
      name: 'name',
      table: 'category',
      data_type: 'varchar',
      default_value: null,
      max_length: 25,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    last_update: {
      name: 'last_update',
      table: 'category',
      data_type: 'timestamp',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
  },
};

export interface CustomerTable {
  customer_id: number;
  store_id: number;
  first_name: string;
  last_name: string;
  email: string;
  address_id: number;
  active: string;
  create_date: Date;
  last_update: Date;
}

export const customerTable: ITable<CustomerTable> = {
  name: 'customer',
  fields: {
    customer_id: {
      name: 'customer_id',
      table: 'customer',
      data_type: 'int',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: true,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    store_id: {
      name: 'store_id',
      table: 'customer',
      data_type: 'int',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: 'store_id',
      foreign_key_table: 'store',
    },
    first_name: {
      name: 'first_name',
      table: 'customer',
      data_type: 'varchar',
      default_value: null,
      max_length: 45,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    last_name: {
      name: 'last_name',
      table: 'customer',
      data_type: 'varchar',
      default_value: null,
      max_length: 45,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    email: {
      name: 'email',
      table: 'customer',
      data_type: 'varchar',
      default_value: 'NULL',
      max_length: 50,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: true,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    address_id: {
      name: 'address_id',
      table: 'customer',
      data_type: 'int',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: 'address_id',
      foreign_key_table: 'address',
    },
    active: {
      name: 'active',
      table: 'customer',
      data_type: 'char',
      default_value: 'Y',
      max_length: 1,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    create_date: {
      name: 'create_date',
      table: 'customer',
      data_type: 'timestamp',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    last_update: {
      name: 'last_update',
      table: 'customer',
      data_type: 'timestamp',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
  },
};

export interface FilmTable {
  film_id: number;
  title: string;
  description: string;
  release_year: string;
  language_id: number;
  original_language_id: number;
  rental_duration: number;
  rental_rate: number;
  length: number;
  replacement_cost: number;
  rating: string;
  special_features: string;
  last_update: Date;
}

export const filmTable: ITable<FilmTable> = {
  name: 'film',
  fields: {
    film_id: {
      name: 'film_id',
      table: 'film',
      data_type: 'int',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: true,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    title: {
      name: 'title',
      table: 'film',
      data_type: 'varchar',
      default_value: null,
      max_length: 255,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    description: {
      name: 'description',
      table: 'film',
      data_type: 'blobsubtypetext',
      default_value: 'NULL',
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: true,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    release_year: {
      name: 'release_year',
      table: 'film',
      data_type: 'varchar',
      default_value: 'NULL',
      max_length: 4,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: true,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    language_id: {
      name: 'language_id',
      table: 'film',
      data_type: 'smallint',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: 'language_id',
      foreign_key_table: 'language',
    },
    original_language_id: {
      name: 'original_language_id',
      table: 'film',
      data_type: 'smallint',
      default_value: 'NULL',
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: true,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: 'language_id',
      foreign_key_table: 'language',
    },
    rental_duration: {
      name: 'rental_duration',
      table: 'film',
      data_type: 'smallint',
      default_value: '3',
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    rental_rate: {
      name: 'rental_rate',
      table: 'film',
      data_type: 'decimal',
      default_value: '4.99',
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    length: {
      name: 'length',
      table: 'film',
      data_type: 'smallint',
      default_value: 'NULL',
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: true,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    replacement_cost: {
      name: 'replacement_cost',
      table: 'film',
      data_type: 'decimal',
      default_value: '19.99',
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    rating: {
      name: 'rating',
      table: 'film',
      data_type: 'varchar',
      default_value: 'G',
      max_length: 10,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: true,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    special_features: {
      name: 'special_features',
      table: 'film',
      data_type: 'varchar',
      default_value: 'NULL',
      max_length: 100,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: true,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    last_update: {
      name: 'last_update',
      table: 'film',
      data_type: 'timestamp',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
  },
};

export interface FilmActorTable {
  actor_id: number;
  film_id: number;
  last_update: Date;
}

export const filmActorTable: ITable<FilmActorTable> = {
  name: 'film_actor',
  fields: {
    actor_id: {
      name: 'actor_id',
      table: 'film_actor',
      data_type: 'int',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: true,
      has_auto_increment: false,
      foreign_key_column: 'actor_id',
      foreign_key_table: 'actor',
    },
    film_id: {
      name: 'film_id',
      table: 'film_actor',
      data_type: 'int',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: 'film_id',
      foreign_key_table: 'film',
    },
    last_update: {
      name: 'last_update',
      table: 'film_actor',
      data_type: 'timestamp',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
  },
};

export interface FilmCategoryTable {
  film_id: number;
  category_id: number;
  last_update: Date;
}

export const filmCategoryTable: ITable<FilmCategoryTable> = {
  name: 'film_category',
  fields: {
    film_id: {
      name: 'film_id',
      table: 'film_category',
      data_type: 'int',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: true,
      has_auto_increment: false,
      foreign_key_column: 'film_id',
      foreign_key_table: 'film',
    },
    category_id: {
      name: 'category_id',
      table: 'film_category',
      data_type: 'smallint',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: 'category_id',
      foreign_key_table: 'category',
    },
    last_update: {
      name: 'last_update',
      table: 'film_category',
      data_type: 'timestamp',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
  },
};

export interface FilmTextTable {
  film_id: number;
  title: string;
  description: string;
}

export const filmTextTable: ITable<FilmTextTable> = {
  name: 'film_text',
  fields: {
    film_id: {
      name: 'film_id',
      table: 'film_text',
      data_type: 'smallint',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: true,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    title: {
      name: 'title',
      table: 'film_text',
      data_type: 'varchar',
      default_value: null,
      max_length: 255,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    description: {
      name: 'description',
      table: 'film_text',
      data_type: 'blobsubtypetext',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: true,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
  },
};

export interface InventoryTable {
  inventory_id: number;
  film_id: number;
  store_id: number;
  last_update: Date;
}

export const inventoryTable: ITable<InventoryTable> = {
  name: 'inventory',
  fields: {
    inventory_id: {
      name: 'inventory_id',
      table: 'inventory',
      data_type: 'int',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: true,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    film_id: {
      name: 'film_id',
      table: 'inventory',
      data_type: 'int',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: 'film_id',
      foreign_key_table: 'film',
    },
    store_id: {
      name: 'store_id',
      table: 'inventory',
      data_type: 'int',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: 'store_id',
      foreign_key_table: 'store',
    },
    last_update: {
      name: 'last_update',
      table: 'inventory',
      data_type: 'timestamp',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
  },
};

export interface StaffTable {
  staff_id: number;
  first_name: string;
  last_name: string;
  address_id: number;
  picture: Blob;
  email: string;
  store_id: number;
  active: number;
  username: string;
  password: string;
  last_update: Date;
}

export const staffTable: ITable<StaffTable> = {
  name: 'staff',
  fields: {
    staff_id: {
      name: 'staff_id',
      table: 'staff',
      data_type: 'smallint',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: true,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    first_name: {
      name: 'first_name',
      table: 'staff',
      data_type: 'varchar',
      default_value: null,
      max_length: 45,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    last_name: {
      name: 'last_name',
      table: 'staff',
      data_type: 'varchar',
      default_value: null,
      max_length: 45,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    address_id: {
      name: 'address_id',
      table: 'staff',
      data_type: 'int',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: 'address_id',
      foreign_key_table: 'address',
    },
    picture: {
      name: 'picture',
      table: 'staff',
      data_type: 'blob',
      default_value: 'NULL',
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: true,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    email: {
      name: 'email',
      table: 'staff',
      data_type: 'varchar',
      default_value: 'NULL',
      max_length: 50,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: true,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    store_id: {
      name: 'store_id',
      table: 'staff',
      data_type: 'int',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: 'store_id',
      foreign_key_table: 'store',
    },
    active: {
      name: 'active',
      table: 'staff',
      data_type: 'smallint',
      default_value: '1',
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    username: {
      name: 'username',
      table: 'staff',
      data_type: 'varchar',
      default_value: null,
      max_length: 16,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    password: {
      name: 'password',
      table: 'staff',
      data_type: 'varchar',
      default_value: 'NULL',
      max_length: 40,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: true,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    last_update: {
      name: 'last_update',
      table: 'staff',
      data_type: 'timestamp',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
  },
};

export interface StoreTable {
  store_id: number;
  manager_staff_id: number;
  address_id: number;
  last_update: Date;
}

export const storeTable: ITable<StoreTable> = {
  name: 'store',
  fields: {
    store_id: {
      name: 'store_id',
      table: 'store',
      data_type: 'int',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: true,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    manager_staff_id: {
      name: 'manager_staff_id',
      table: 'store',
      data_type: 'smallint',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: 'staff_id',
      foreign_key_table: 'staff',
    },
    address_id: {
      name: 'address_id',
      table: 'store',
      data_type: 'int',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: 'address_id',
      foreign_key_table: 'address',
    },
    last_update: {
      name: 'last_update',
      table: 'store',
      data_type: 'timestamp',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
  },
};

export interface PaymentTable {
  payment_id: number;
  customer_id: number;
  staff_id: number;
  rental_id: number;
  amount: number;
  payment_date: Date;
  last_update: Date;
}

export const paymentTable: ITable<PaymentTable> = {
  name: 'payment',
  fields: {
    payment_id: {
      name: 'payment_id',
      table: 'payment',
      data_type: 'int',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: true,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    customer_id: {
      name: 'customer_id',
      table: 'payment',
      data_type: 'int',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: 'customer_id',
      foreign_key_table: 'customer',
    },
    staff_id: {
      name: 'staff_id',
      table: 'payment',
      data_type: 'smallint',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: 'staff_id',
      foreign_key_table: 'staff',
    },
    rental_id: {
      name: 'rental_id',
      table: 'payment',
      data_type: 'int',
      default_value: 'NULL',
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: true,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: 'rental_id',
      foreign_key_table: 'rental',
    },
    amount: {
      name: 'amount',
      table: 'payment',
      data_type: 'decimal',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    payment_date: {
      name: 'payment_date',
      table: 'payment',
      data_type: 'timestamp',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    last_update: {
      name: 'last_update',
      table: 'payment',
      data_type: 'timestamp',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
  },
};

export interface RentalTable {
  rental_id: number;
  rental_date: Date;
  inventory_id: number;
  customer_id: number;
  return_date: Date;
  staff_id: number;
  last_update: Date;
}

export const rentalTable: ITable<RentalTable> = {
  name: 'rental',
  fields: {
    rental_id: {
      name: 'rental_id',
      table: 'rental',
      data_type: 'int',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: true,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    rental_date: {
      name: 'rental_date',
      table: 'rental',
      data_type: 'timestamp',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    inventory_id: {
      name: 'inventory_id',
      table: 'rental',
      data_type: 'int',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: 'inventory_id',
      foreign_key_table: 'inventory',
    },
    customer_id: {
      name: 'customer_id',
      table: 'rental',
      data_type: 'int',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: 'customer_id',
      foreign_key_table: 'customer',
    },
    return_date: {
      name: 'return_date',
      table: 'rental',
      data_type: 'timestamp',
      default_value: 'NULL',
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: true,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
    staff_id: {
      name: 'staff_id',
      table: 'rental',
      data_type: 'smallint',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: 'staff_id',
      foreign_key_table: 'staff',
    },
    last_update: {
      name: 'last_update',
      table: 'rental',
      data_type: 'timestamp',
      default_value: null,
      max_length: null,
      numeric_precision: null,
      numeric_scale: null,
      is_generated: false,
      is_nullable: false,
      is_unique: false,
      is_primary_key: false,
      has_auto_increment: false,
      foreign_key_column: null,
      foreign_key_table: null,
    },
  },
};
